version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3'
    ports:
      - "80:80"
    tty: true
    volumes:
      - ./app:/code/app
    environment:
      PORT: 80
